# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tiago <tiago@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/10/23 14:39:28 by tsimao-g          #+#    #+#              #
#    Updated: 2025/11/07 03:20:08 by tiago            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS			=	ft_strlen.c ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
					ft_isdigit.c ft_isprint.c ft_memchr.c ft_memcmp.c ft_memcpy.c \
					ft_memmove.c  ft_memset.c  ft_strchr.c ft_strdup.c ft_strlcat.c \
					ft_strlcpy.c ft_atoi.c ft_strncmp.c ft_strnstr.c ft_strrchr.c \
					ft_tolower.c ft_toupper.c ft_strjoin.c ft_calloc.c ft_strtrim.c \
					ft_putchar_fd.c ft_putstr_fd.c ft_putnbr_fd.c ft_putendl_fd.c \
					ft_strmapi.c ft_striteri.c ft_itoa.c ft_split.c ft_substr.c

BONUS			=	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c\
					ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c\
					ft_lstmap.c
					
OBJ_DIR			=	mandatory
BONUS_DIR		=	bonus

OBJS			=	$(addprefix $(OBJ_DIR)/, $(SRCS:.c=.o))
BONUS_OBJS		=	$(addprefix $(BONUS_DIR)/, $(BONUS:.c=.o))

CC				=	cc
RM				=	rm -f
CFLAGS			=	-Wall -Wextra -Werror
NAME			=	libft.a

all:			$(NAME)

$(NAME):		$(OBJS)
				ar rcs $(NAME) $(OBJS)

bonus:			$(BONUS_OBJS)
				ar rcs $(NAME) $(OBJS) $(BONUS_OBJS)

$(OBJ_DIR)/%.o:	%.c
				@mkdir -p $(OBJ_DIR)
				$(CC) $(CFLAGS) -c $< -o $@

$(BONUS_DIR)/%.o:	%.c
				@mkdir -p $(BONUS_DIR)
				$(CC) $(CFLAGS) -c $< -o $@

clean:
				$(RM) -r $(OBJ_DIR) $(BONUS_DIR)

fclean:			clean
				$(RM) $(NAME)

re:				fclean $(NAME)

.PHONY:			all bonus clean fclean re